name: Music Bot Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pytgcalls (specific version)
        run: |
          pip install pytgcalls==2.0.0  # Add the compatible version of pytgcalls

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the bot
        run: |
          python3 main.py  # Run your bot script
