name: Music Bot Deployment

on:
  push:
    branches:
      - main  # Ye workflow tab run hoga jab aap main branch pe push karenge
  workflow_dispatch:  # Manually run karne ke liye

jobs:
  build:
    runs-on: ubuntu-latest  # Ye workflow Ubuntu environment mein run hoga

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Repository ko checkout karte hain

      - name: Set up Python
        uses: actions/setup-python@v4  # Python ko setup karte hain
        with:
          python-version: '3.9'  # Python version set karein

      - name: Install pytgcalls
        run: |
          pip install --upgrade pytgcalls  # Pytgcalls ko upgrade karte hain

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Dependencies ko install karte hain

      - name: Run the bot
        run: |
          python3 main.py  # Bot script ko run karte hain
